import Image from "next/image";
import { Navbar } from "./components/navbar";
import { Button } from "@/components/ui/button";
import { CircleArrowRight } from "lucide-react";
import { Footer } from "./components/footer";
import BannerHome from "./components/banner-home";
import { UseModal } from "../hooks/use-modal";
import ToastNotification from "./components/ToastNotification";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Metadata } from "next";
import { MobileSidebar } from "./components/mobile-sidebar";
const inter = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <ToastNotification />
        <>
          <div className="flex flex-col min-h-[100vh]">
            <div className="text-center bg-black text-white p-2 text-sm font-[500]">
              Đễ được hỗ trợ nhanh nhất bạn liên hệ mình qua
            </div>
            <div className="box shadow-[0_2px_2px_-2px_gray]">
              <MobileSidebar />
              <Navbar />
            </div>
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
        </>
      </body>
    </html>
  );
}
